name: Angular Build

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    tests-and-build:
        name: Angular Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: package-lock.json
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test:ci
            - name: Build
              run: npm run build
